## LINEAR REGRESSION

In [10]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import scale

boston = load_boston()
X,y = scale(boston.data), boston.target

In [18]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X, y)
regression.score(X,y)

0.7406426641094095

In [25]:
print ([a + ':' + str(round(b,1)) for a,b in zip(boston.feature_names, regression.coef_)])

['CRIM:-0.9', 'ZN:1.1', 'INDUS:0.1', 'CHAS:0.7', 'NOX:-2.1', 'RM:2.7', 'AGE:0.0', 'DIS:-3.1', 'RAD:2.7', 'TAX:-2.1', 'PTRATIO:-2.1', 'B:0.8', 'LSTAT:-3.7']


## ONE HOT ENCODING

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()
enc = OneHotEncoder()

qualitative = ['red', 'red', 'green', 'blue', 'red', 'blue', 'blue', 'green']
labels = lbl.fit_transform(qualitative).reshape(8,1)

print(enc.fit_transform(labels).toarray())

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


## POLYNOMIAL FEATURES

In [36]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

pf = PolynomialFeatures(degree=2)
poly_X = pf.fit_transform(X)
X_train, X_test, y_train, y_test = (
    train_test_split(poly_X, y, test_size=0.33, random_state=42))
poly_X

array([[ 1.        , -0.41978194,  0.28482986, ...,  0.19452681,
        -0.47437883,  1.15683427],
       [ 1.        , -0.41733926, -0.48772236, ...,  0.19452681,
        -0.21719133,  0.24249653],
       [ 1.        , -0.41734159, -0.48772236, ...,  0.15715436,
        -0.47917217,  1.46102192],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ...,  0.19452681,
        -0.43357505,  0.9663826 ],
       [ 1.        , -0.40776407, -0.48772236, ...,  0.16259032,
        -0.34891116,  0.74874691],
       [ 1.        , -0.41500016, -0.48772236, ...,  0.19452681,
        -0.29508947,  0.44763905]])

In [37]:
from sklearn.linear_model import Ridge
reg_regression = Ridge(alpha=0.1, normalize=True)
reg_regression.fit(X_train, y_train)
r2_score(y_test, reg_regression.predict(X_test))

0.8197102281821296

## USING BINARY-RESPONSE CLASSIFICATION

In [46]:
import numpy as np

a = np.array([0,0,0,0,1,1,1,1])
b = np.array([1,2,3,4,5,6,7,8]).reshape(8,1)

In [47]:
from sklearn.linear_model import  LinearRegression

regression = LinearRegression()
regression.fit(b, a)
print(regression.predict(b)>0.5)

[False False False False  True  True  True  True]
