# LIST COMPREHENSIONS BASIC

In [1]:
#FOR LOOP
h_letters = []

for x in 'human':
    h_letters.append(x)

h_letters

['h', 'u', 'm', 'a', 'n']

In [2]:
#LIST COMPREHENSION
h_letters = [x for x in 'human']
h_letters

['h', 'u', 'm', 'a', 'n']

In [3]:
#USING LAMBDA FUNCS
h_letters = list(map(lambda x: x, 'human'))
h_letters

['h', 'u', 'm', 'a', 'n']

In [4]:
#LIST COMPREHENSION CONDITIONAL
nums = [x for x in range(20) if x%2==0]
nums

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
#LIST COMPREHENSION NESTED IF
nums = [x for x in range(100) if x%2==0 if x%5==0]
nums

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [9]:
#LIST COMPREHENSION IF ELSE
obj = ["Even" if i%2==0 else "Odd" for i in range(10)]
obj

['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']

In [17]:
#LIST COMPREHENSION NESTED lOOP
transposed = []
matrix = [[1,2,3,4],[4,5,6,7]]

for i in range(len(matrix[0])):
    transposed_row = []
    
    for row in matrix:
        transposed_row.append(row[i])
    
    transposed.append(transposed_row)

transposed

[[1, 4], [2, 5], [3, 6], [4, 7]]

# ARRAYS AND MATRICES

In [18]:
import numpy as np

In [41]:
x = np.array([[1,2,3],[4,5,6]])
y = x[0:,2]
y

array([3, 6])

In [42]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.ones([5,5], dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [47]:
x = np.mat([[1,2,3],[4,5,6]])
x

matrix([[1, 2, 3],
        [4, 5, 6]])

In [49]:
np.asarray(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
x = np.mat([[1,2,3],[4,5,6]])
y = np.mat([[10,11],[20,21],[30,31]])



matrix([[140, 146],
        [320, 335]])

# DICTIONARY

In [1]:
captains = {}
captains["Enterprise"] = "Kirk"
captains["Enterprise D"] = "Picard"
captains["Deep Space Nine"] = "Sisko"

In [2]:
captains["Enterprise"]

'Kirk'

In [5]:
print(captains.get("Enterprise"))

Kirk


In [10]:
for x in captains:
    print(x + " : "+ captains[x])

Enterprise : Kirk
Enterprise D : Picard
Deep Space Nine : Sisko
